insert into Dishes (Name, Category, Calories) values ('Cheeseburger', 'Glavno jelo', 223);
insert into Dishes (Name, Category, Calories) values ('Grilled Chicken Salad', 'Desert', 397);
insert into Dishes (Name, Category, Calories) values ('Margherita Pizza', 'Predjelo', 984);
insert into Dishes (Name, Category, Calories) values ('Caesar Salad', 'Predjelo', 205);
insert into Dishes (Name, Category, Calories) values ('Beef Wellington', 'Predjelo', 114);
insert into Dishes (Name, Category, Calories) values ('Spaghetti Bolognese', 'Desert', 58);
insert into Dishes (Name, Category, Calories) values ('Chicken Alfredo', 'Desert', 787);
insert into Dishes (Name, Category, Calories) values ('Fish Tacos', 'Predjelo', 213);
insert into Dishes (Name, Category, Calories) values ('Lamb Chops', 'Glavno jelo', 837);
insert into Dishes (Name, Category, Calories) values ('Mushroom Risotto', 'Desert', 639);
insert into Dishes (Name, Category, Calories) values ('Veggie Burger', 'Desert', 448);
insert into Dishes (Name, Category, Calories) values ('Chicken Parmesan', 'Glavno jelo', 87);
insert into Dishes (Name, Category, Calories) values ('Shrimp Scampi', 'Desert', 710);
insert into Dishes (Name, Category, Calories) values ('Rib-eye Steak', 'Desert', 488);
insert into Dishes (Name, Category, Calories) values ('Chicken Quesadilla', 'Glavno jelo', 759);
insert into Dishes (Name, Category, Calories) values ('Pad Thai', 'Glavno jelo', 67);
insert into Dishes (Name, Category, Calories) values ('Lasagna', 'Desert', 878);
insert into Dishes (Name, Category, Calories) values ('Stuffed Bell Peppers', 'Glavno jelo', 69);
insert into Dishes (Name, Category, Calories) values ('Peking Duck', 'Desert', 390);
insert into Dishes (Name, Category, Calories) values ('Fish and Chips', 'Desert', 429);
insert into Dishes (Name, Category, Calories) values ('Chicken Tikka Masala', 'Desert', 811);
insert into Dishes (Name, Category, Calories) values ('Pork Schnitzel', 'Glavno jelo', 618);
insert into Dishes (Name, Category, Calories) values ('Grilled Salmon', 'Glavno jelo', 369);
insert into Dishes (Name, Category, Calories) values ('Eggplant Parmesan', 'Desert', 794);
insert into Dishes (Name, Category, Calories) values ('Fettuccine Carbonara', 'Glavno jelo', 587);
insert into Dishes (Name, Category, Calories) values ('Beef Burritos', 'Glavno jelo', 888);
insert into Dishes (Name, Category, Calories) values ('Chicken Fried Rice', 'Predjelo', 476);
insert into Dishes (Name, Category, Calories) values ('Shrimp Tempura', 'Desert', 636);
insert into Dishes (Name, Category, Calories) values ('Duck Confit', 'Glavno jelo', 634);
insert into Dishes (Name, Category, Calories) values ('Roasted Vegetables', 'Desert', 617);
insert into Dishes (Name, Category, Calories) values ('Tuna Tartare', 'Desert', 523);
insert into Dishes (Name, Category, Calories) values ('Beef Stroganoff', 'Desert', 174);
insert into Dishes (Name, Category, Calories) values ('Clam Chowder', 'Predjelo', 122);
insert into Dishes (Name, Category, Calories) values ('Grilled Shrimp Skewers', 'Predjelo', 803);
insert into Dishes (Name, Category, Calories) values ('Sweet and Sour Chicken', 'Glavno jelo', 861);
insert into Dishes (Name, Category, Calories) values ('Chicken Wings', 'Desert', 978);
insert into Dishes (Name, Category, Calories) values ('Meatball Sub', 'Predjelo', 309);
insert into Dishes (Name, Category, Calories) values ('Veggie Pizza', 'Desert', 310);
insert into Dishes (Name, Category, Calories) values ('Crab Cakes', 'Glavno jelo', 913);
insert into Dishes (Name, Category, Calories) values ('Chicken Caesar Wrap', 'Predjelo', 342);
insert into Dishes (Name, Category, Calories) values ('Spicy Tuna Roll', 'Glavno jelo', 137);
insert into Dishes (Name, Category, Calories) values ('Pork Belly', 'Desert', 904);
insert into Dishes (Name, Category, Calories) values ('Beef Fajitas', 'Predjelo', 112);
insert into Dishes (Name, Category, Calories) values ('Prawn Cocktail', 'Predjelo', 308);
insert into Dishes (Name, Category, Calories) values ('Beef Ribs', 'Glavno jelo', 208);
insert into Dishes (Name, Category, Calories) values ('Mushroom Soup', 'Predjelo', 506);
insert into Dishes (Name, Category, Calories) values ('Grilled Vegetables', 'Predjelo', 511);
insert into Dishes (Name, Category, Calories) values ('Roasted Chicken', 'Desert', 944);
insert into Dishes (Name, Category, Calories) values ('Chili Con Carne', 'Predjelo', 654);
insert into Dishes (Name, Category, Calories) values ('Fish Curry', 'Predjelo', 629);
insert into Dishes (Name, Category, Calories) values ('BBQ Ribs', 'Predjelo', 712);
insert into Dishes (Name, Category, Calories) values ('Chicken Nuggets', 'Predjelo', 146);
insert into Dishes (Name, Category, Calories) values ('Paella', 'Glavno jelo', 911);
insert into Dishes (Name, Category, Calories) values ('Veal Marsala', 'Desert', 750);
insert into Dishes (Name, Category, Calories) values ('Beef Empanadas', 'Glavno jelo', 277);
insert into Dishes (Name, Category, Calories) values ('Garlic Bread', 'Desert', 561);
insert into Dishes (Name, Category, Calories) values ('Chicken and Waffles', 'Predjelo', 562);
insert into Dishes (Name, Category, Calories) values ('Beef Kebabs', 'Predjelo', 465);
insert into Dishes (Name, Category, Calories) values ('Lobster Roll', 'Desert', 142);
insert into Dishes (Name, Category, Calories) values ('Baked Ziti', 'Predjelo', 634);
insert into Dishes (Name, Category, Calories) values ('Beef Tacos', 'Glavno jelo', 806);
insert into Dishes (Name, Category, Calories) values ('Crab Legs', 'Predjelo', 672);
insert into Dishes (Name, Category, Calories) values ('Shrimp Po'' Boy', 'Glavno jelo', 546);
insert into Dishes (Name, Category, Calories) values ('Shrimp Ceviche', 'Glavno jelo', 441);
insert into Dishes (Name, Category, Calories) values ('Grilled Cheese Sandwich', 'Predjelo', 284);
insert into Dishes (Name, Category, Calories) values ('Nachos', 'Desert', 277);
insert into Dishes (Name, Category, Calories) values ('Beef Lasagna', 'Desert', 903);
insert into Dishes (Name, Category, Calories) values ('Chicken Souvlaki', 'Desert', 765);
insert into Dishes (Name, Category, Calories) values ('Pork Tenderloin', 'Predjelo', 432);
insert into Dishes (Name, Category, Calories) values ('Beef Skewers', 'Predjelo', 299);
insert into Dishes (Name, Category, Calories) values ('Chicken Satay', 'Glavno jelo', 340);
insert into Dishes (Name, Category, Calories) values ('Grilled Tuna', 'Predjelo', 267);
insert into Dishes (Name, Category, Calories) values ('Tuna Salad', 'Desert', 547);
insert into Dishes (Name, Category, Calories) values ('Roasted Pork', 'Desert', 525);
insert into Dishes (Name, Category, Calories) values ('Vegetable Stir Fry', 'Glavno jelo', 522);
insert into Dishes (Name, Category, Calories) values ('Grilled Octopus', 'Desert', 273);
insert into Dishes (Name, Category, Calories) values ('BBQ Pulled Pork', 'Predjelo', 758);
insert into Dishes (Name, Category, Calories) values ('Lamb Shank', 'Predjelo', 798);
insert into Dishes (Name, Category, Calories) values ('Crab Linguine', 'Glavno jelo', 382);
insert into Dishes (Name, Category, Calories) values ('Mushroom Tarts', 'Glavno jelo', 986);
insert into Dishes (Name, Category, Calories) values ('Broccoli and Cheese', 'Predjelo', 999);
insert into Dishes (Name, Category, Calories) values ('Thai Green Curry', 'Desert', 196);
insert into Dishes (Name, Category, Calories) values ('Grilled Veal', 'Desert', 143);
insert into Dishes (Name, Category, Calories) values ('Grilled Chicken Tenders', 'Desert', 525);
insert into Dishes (Name, Category, Calories) values ('Caprese Salad', 'Glavno jelo', 564);
insert into Dishes (Name, Category, Calories) values ('Beef Kofta', 'Desert', 933);
insert into Dishes (Name, Category, Calories) values ('Moussaka', 'Desert', 97);
insert into Dishes (Name, Category, Calories) values ('Seafood Paella', 'Predjelo', 210);
insert into Dishes (Name, Category, Calories) values ('Chicken Shawarma', 'Predjelo', 867);
insert into Dishes (Name, Category, Calories) values ('Chicken and Rice', 'Glavno jelo', 377);
insert into Dishes (Name, Category, Calories) values ('Grilled Trout', 'Predjelo', 186);
insert into Dishes (Name, Category, Calories) values ('Lobster Bisque', 'Predjelo', 775);
insert into Dishes (Name, Category, Calories) values ('Baked Salmon', 'Predjelo', 167);
insert into Dishes (Name, Category, Calories) values ('Spaghetti Aglio e Olio', 'Glavno jelo', 434);
insert into Dishes (Name, Category, Calories) values ('Crispy Chicken Sandwich', 'Predjelo', 829);
insert into Dishes (Name, Category, Calories) values ('Chili Dog', 'Glavno jelo', 278);
insert into Dishes (Name, Category, Calories) values ('French Toast', 'Predjelo', 72);
insert into Dishes (Name, Category, Calories) values ('Bacon-Wrapped Scallops', 'Desert', 199);
insert into Dishes (Name, Category, Calories) values ('Stuffed Mushrooms', 'Glavno jelo', 223);
insert into Dishes (Name, Category, Calories) values ('Egg Salad', 'Glavno jelo', 406);
insert into Dishes (Name, Category, Calories) values ('Gyro', 'Glavno jelo', 302);
insert into Dishes (Name, Category, Calories) values ('Grilled Pork Chops', 'Glavno jelo', 327);
insert into Dishes (Name, Category, Calories) values ('Philly Cheesesteak', 'Desert', 848);
insert into Dishes (Name, Category, Calories) values ('Chicken Tenders', 'Desert', 560);
insert into Dishes (Name, Category, Calories) values ('Tofu Stir Fry', 'Predjelo', 303);
insert into Dishes (Name, Category, Calories) values ('Shrimp Fried Rice', 'Predjelo', 273);
insert into Dishes (Name, Category, Calories) values ('Beef Empanada', 'Predjelo', 281);
insert into Dishes (Name, Category, Calories) values ('Grilled Lamb Kebabs', 'Glavno jelo', 406);
insert into Dishes (Name, Category, Calories) values ('Vegetable Samosas', 'Desert', 807);
insert into Dishes (Name, Category, Calories) values ('Pasta Primavera', 'Desert', 449);
insert into Dishes (Name, Category, Calories) values ('Sweet Potato Fries', 'Predjelo', 901);
insert into Dishes (Name, Category, Calories) values ('Croque Monsieur', 'Desert', 474);
insert into Dishes (Name, Category, Calories) values ('Grilled Fish', 'Glavno jelo', 917);
insert into Dishes (Name, Category, Calories) values ('Lamb Stew', 'Predjelo', 392);
insert into Dishes (Name, Category, Calories) values ('Beef Wellington', 'Glavno jelo', 259);
insert into Dishes (Name, Category, Calories) values ('Chicken Kiev', 'Glavno jelo', 947);
insert into Dishes (Name, Category, Calories) values ('Mozzarella Sticks', 'Desert', 751);
insert into Dishes (Name, Category, Calories) values ('Fish Tacos', 'Predjelo', 864);
insert into Dishes (Name, Category, Calories) values ('Eggplant Rollatini', 'Glavno jelo', 821);
insert into Dishes (Name, Category, Calories) values ('Beef Burrito Bowl', 'Desert', 294);
insert into Dishes (Name, Category, Calories) values ('Chicken Marsala', 'Desert', 974);
insert into Dishes (Name, Category, Calories) values ('Grilled Fish Tacos', 'Glavno jelo', 208);
insert into Dishes (Name, Category, Calories) values ('Lamb Biryani', 'Glavno jelo', 398);
insert into Dishes (Name, Category, Calories) values ('Spicy Chicken Wings', 'Desert', 482);
insert into Dishes (Name, Category, Calories) values ('Chicken Soup', 'Glavno jelo', 823);
insert into Dishes (Name, Category, Calories) values ('Shrimp Gumbo', 'Glavno jelo', 910);
insert into Dishes (Name, Category, Calories) values ('Baked Potato Soup', 'Glavno jelo', 859);
insert into Dishes (Name, Category, Calories) values ('Chili Cheese Fries', 'Predjelo', 310);
insert into Dishes (Name, Category, Calories) values ('Pasta Bolognese', 'Glavno jelo', 852);
insert into Dishes (Name, Category, Calories) values ('Chicken Burrito', 'Predjelo', 893);
insert into Dishes (Name, Category, Calories) values ('Steak Frites', 'Predjelo', 772);
insert into Dishes (Name, Category, Calories) values ('Pasta Carbonara', 'Glavno jelo', 934);
insert into Dishes (Name, Category, Calories) values ('Beef Steak', 'Glavno jelo', 337);
insert into Dishes (Name, Category, Calories) values ('Shrimp and Grits', 'Desert', 539);
insert into Dishes (Name, Category, Calories) values ('Egg Salad Sandwich', 'Glavno jelo', 299);
insert into Dishes (Name, Category, Calories) values ('Buffalo Wings', 'Glavno jelo', 748);
insert into Dishes (Name, Category, Calories) values ('Jambalaya', 'Glavno jelo', 396);
insert into Dishes (Name, Category, Calories) values ('Tofu Burger', 'Desert', 608);
insert into Dishes (Name, Category, Calories) values ('Fajita Bowl', 'Desert', 703);
insert into Dishes (Name, Category, Calories) values ('Prawn Risotto', 'Glavno jelo', 96);
insert into Dishes (Name, Category, Calories) values ('Grilled Calamari', 'Desert', 446);
insert into Dishes (Name, Category, Calories) values ('Crab Soup', 'Predjelo', 140);
insert into Dishes (Name, Category, Calories) values ('Stuffed Squash', 'Desert', 283);
insert into Dishes (Name, Category, Calories) values ('Lobster Mac and Cheese', 'Desert', 758);
insert into Dishes (Name, Category, Calories) values ('Beef Ragu', 'Predjelo', 826);
insert into Dishes (Name, Category, Calories) values ('Meatloaf', 'Predjelo', 378);
insert into Dishes (Name, Category, Calories) values ('Chicken and Dumplings', 'Desert', 137);
insert into Dishes (Name, Category, Calories) values ('Clams Casino', 'Predjelo', 534);
insert into Dishes (Name, Category, Calories) values ('Grilled Veggie Wrap', 'Glavno jelo', 295);
insert into Dishes (Name, Category, Calories) values ('Mahi Mahi Tacos', 'Desert', 338);
insert into Dishes (Name, Category, Calories) values ('Shrimp Skewers', 'Glavno jelo', 576);
insert into Dishes (Name, Category, Calories) values ('Fish Fry', 'Glavno jelo', 173);
insert into Dishes (Name, Category, Calories) values ('Moussaka', 'Glavno jelo', 361);
insert into Dishes (Name, Category, Calories) values ('Pork Ribs', 'Predjelo', 81);
insert into Dishes (Name, Category, Calories) values ('Grilled Sardines', 'Glavno jelo', 890);
insert into Dishes (Name, Category, Calories) values ('Chicken Piccata', 'Predjelo', 697);
insert into Dishes (Name, Category, Calories) values ('Sashimi', 'Desert', 923);
insert into Dishes (Name, Category, Calories) values ('Grilled Octopus', 'Desert', 813);
insert into Dishes (Name, Category, Calories) values ('Chicken Burger', 'Desert', 408);
insert into Dishes (Name, Category, Calories) values ('Caesar Wrap', 'Desert', 227);
insert into Dishes (Name, Category, Calories) values ('Beef Enchiladas', 'Glavno jelo', 519);
insert into Dishes (Name, Category, Calories) values ('Fried Catfish', 'Desert', 110);
insert into Dishes (Name, Category, Calories) values ('Spaghetti with Meatballs', 'Predjelo', 813);
insert into Dishes (Name, Category, Calories) values ('Chicken Chow Mein', 'Desert', 656);
insert into Dishes (Name, Category, Calories) values ('Pappardelle Pasta', 'Predjelo', 759);
insert into Dishes (Name, Category, Calories) values ('Grilled Lobster', 'Desert', 444);
insert into Dishes (Name, Category, Calories) values ('Vegetable Tempura', 'Glavno jelo', 598);
insert into Dishes (Name, Category, Calories) values ('Crab Cakes', 'Desert', 967);
insert into Dishes (Name, Category, Calories) values ('Chicken Stir Fry', 'Glavno jelo', 217);
insert into Dishes (Name, Category, Calories) values ('Shrimp Risotto', 'Glavno jelo', 904);
insert into Dishes (Name, Category, Calories) values ('Fish Sandwich', 'Desert', 149);
insert into Dishes (Name, Category, Calories) values ('Grilled Shrimp Tacos', 'Predjelo', 55);
insert into Dishes (Name, Category, Calories) values ('Chicken Queso', 'Predjelo', 264);
insert into Dishes (Name, Category, Calories) values ('Salmon with Asparagus', 'Desert', 85);
insert into Dishes (Name, Category, Calories) values ('Calzone', 'Predjelo', 285);
insert into Dishes (Name, Category, Calories) values ('Stuffed Chicken Breast', 'Desert', 864);
insert into Dishes (Name, Category, Calories) values ('Beef Chili', 'Predjelo', 764);
insert into Dishes (Name, Category, Calories) values ('Peking Duck', 'Glavno jelo', 458);
insert into Dishes (Name, Category, Calories) values ('Philly Cheesesteak Sandwich', 'Glavno jelo', 730);
insert into Dishes (Name, Category, Calories) values ('Quiche', 'Glavno jelo', 138);
insert into Dishes (Name, Category, Calories) values ('Marinated Chicken', 'Desert', 291);
insert into Dishes (Name, Category, Calories) values ('Baked Ziti with Meatballs', 'Predjelo', 65);
insert into Dishes (Name, Category, Calories) values ('Pita Bread with Hummus', 'Predjelo', 326);
insert into Dishes (Name, Category, Calories) values ('Cucumber Sandwiches', 'Predjelo', 944);
insert into Dishes (Name, Category, Calories) values ('Jerk Chicken', 'Desert', 487);
insert into Dishes (Name, Category, Calories) values ('Roast Beef Sandwich', 'Predjelo', 163);
insert into Dishes (Name, Category, Calories) values ('Fried Green Tomatoes', 'Glavno jelo', 386);
insert into Dishes (Name, Category, Calories) values ('Pimento Cheese Sandwich', 'Glavno jelo', 895);
insert into Dishes (Name, Category, Calories) values ('Chicken Drumsticks', 'Desert', 654);
insert into Dishes (Name, Category, Calories) values ('BBQ Chicken', 'Glavno jelo', 893);
insert into Dishes (Name, Category, Calories) values ('Tofu Stir Fry', 'Predjelo', 576);
insert into Dishes (Name, Category, Calories) values ('Grilled Portobello Mushroom', 'Desert', 417);
insert into Dishes (Name, Category, Calories) values ('Lobster Tail', 'Predjelo', 65);
insert into Dishes (Name, Category, Calories) values ('Grilled Pork Belly', 'Predjelo', 504);
insert into Dishes (Name, Category, Calories) values ('Chicken Cacciatore', 'Glavno jelo', 973);
insert into Dishes (Name, Category, Calories) values ('Shrimp and Lobster Ravioli', 'Glavno jelo', 703);
insert into Dishes (Name, Category, Calories) values ('Roast Duck', 'Glavno jelo', 79);
insert into Dishes (Name, Category, Calories) values ('Beef Croquettes', 'Glavno jelo', 309);
insert into Dishes (Name, Category, Calories) values ('Grilled Eggplant', 'Desert', 74);
insert into Dishes (Name, Category, Calories) values ('Clam Chowder Bread Bowl', 'Desert', 179);
insert into Dishes (Name, Category, Calories) values ('Pan Seared Tuna', 'Predjelo', 760);
insert into Dishes (Name, Category, Calories) values ('Baked Chicken Thighs', 'Predjelo', 692);
insert into Dishes (Name, Category, Calories) values ('Veal Parmesan', 'Glavno jelo', 330);
insert into Dishes (Name, Category, Calories) values ('Grilled Pork Loin', 'Glavno jelo', 362);
insert into Dishes (Name, Category, Calories) values ('Fennel Salad', 'Glavno jelo', 348);
insert into Dishes (Name, Category, Calories) values ('Grilled Chicken Caesar Salad', 'Glavno jelo', 292);
insert into Dishes (Name, Category, Calories) values ('Roasted Duck', 'Glavno jelo', 479);
insert into Dishes (Name, Category, Calories) values ('Garlic Shrimp Pasta', 'Predjelo', 771);
insert into Dishes (Name, Category, Calories) values ('Smoked Salmon Salad', 'Desert', 863);
insert into Dishes (Name, Category, Calories) values ('Grilled Peppers', 'Desert', 972);
insert into Dishes (Name, Category, Calories) values ('Lemon Chicken', 'Glavno jelo', 66);
insert into Dishes (Name, Category, Calories) values ('Pork Chop Sandwich', 'Desert', 945);
insert into Dishes (Name, Category, Calories) values ('Caviar on Toast', 'Glavno jelo', 807);
insert into Dishes (Name, Category, Calories) values ('Chicken Spring Rolls', 'Predjelo', 465);
insert into Dishes (Name, Category, Calories) values ('Pork Taco', 'Predjelo', 369);
insert into Dishes (Name, Category, Calories) values ('Grilled Sea Bass', 'Glavno jelo', 956);
insert into Dishes (Name, Category, Calories) values ('Piri Piri Chicken', 'Desert', 948);
insert into Dishes (Name, Category, Calories) values ('Salmon Fillet', 'Desert', 245);
insert into Dishes (Name, Category, Calories) values ('Grilled Lamb', 'Predjelo', 194);
insert into Dishes (Name, Category, Calories) values ('Cheesesteak Fries', 'Predjelo', 315);
insert into Dishes (Name, Category, Calories) values ('Veggie Stir Fry', 'Glavno jelo', 138);
insert into Dishes (Name, Category, Calories) values ('Garlic Parmesan Fries', 'Desert', 288);
insert into Dishes (Name, Category, Calories) values ('Fish Fillet', 'Predjelo', 982);
insert into Dishes (Name, Category, Calories) values ('Pork Burrito', 'Desert', 786);
insert into Dishes (Name, Category, Calories) values ('Grilled Shrimp', 'Glavno jelo', 987);
insert into Dishes (Name, Category, Calories) values ('Grilled Lobster Tails', 'Predjelo', 313);
insert into Dishes (Name, Category, Calories) values ('Chicken Fajita Salad', 'Predjelo', 296);
insert into Dishes (Name, Category, Calories) values ('Teriyaki Chicken', 'Desert', 685);
insert into Dishes (Name, Category, Calories) values ('Pork Tenderloin Sandwich', 'Predjelo', 322);
insert into Dishes (Name, Category, Calories) values ('Pasta with Garlic Sauce', 'Desert', 573);
insert into Dishes (Name, Category, Calories) values ('Roast Chicken', 'Glavno jelo', 997);
insert into Dishes (Name, Category, Calories) values ('Sweet Potato Mash', 'Glavno jelo', 817);
insert into Dishes (Name, Category, Calories) values ('Chicken Bruschetta', 'Predjelo', 577);
insert into Dishes (Name, Category, Calories) values ('Veggie Burrito', 'Predjelo', 292);
insert into Dishes (Name, Category, Calories) values ('Chicken Banh Mi', 'Glavno jelo', 228);
insert into Dishes (Name, Category, Calories) values ('Lobster Bisque Soup', 'Glavno jelo', 510);
insert into Dishes (Name, Category, Calories) values ('Macaroni Salad', 'Glavno jelo', 202);
insert into Dishes (Name, Category, Calories) values ('Chicken Sausage', 'Glavno jelo', 579);
insert into Dishes (Name, Category, Calories) values ('Sautéed Mushrooms', 'Predjelo', 689);
insert into Dishes (Name, Category, Calories) values ('Spicy Lamb Kofta', 'Predjelo', 126);
insert into Dishes (Name, Category, Calories) values ('Lamb Biryani', 'Glavno jelo', 719);
insert into Dishes (Name, Category, Calories) values ('Shakshuka', 'Predjelo', 687);
insert into Dishes (Name, Category, Calories) values ('Cucumber and Tomato Salad', 'Predjelo', 645);
insert into Dishes (Name, Category, Calories) values ('Quinoa Salad', 'Glavno jelo', 230);
insert into Dishes (Name, Category, Calories) values ('Lobster Risotto', 'Glavno jelo', 853);
insert into Dishes (Name, Category, Calories) values ('Chicken and Broccoli', 'Desert', 378);
insert into Dishes (Name, Category, Calories) values ('Prawns in Garlic Sauce', 'Predjelo', 804);
insert into Dishes (Name, Category, Calories) values ('Chilled Soup', 'Glavno jelo', 492);
insert into Dishes (Name, Category, Calories) values ('Crab and Avocado Salad', 'Glavno jelo', 427);
insert into Dishes (Name, Category, Calories) values ('Tofu Tacos', 'Predjelo', 108);
insert into Dishes (Name, Category, Calories) values ('Grilled Scallops', 'Predjelo', 63);
insert into Dishes (Name, Category, Calories) values ('Tuna Steak', 'Glavno jelo', 345);
insert into Dishes (Name, Category, Calories) values ('Seared Ahi Tuna', 'Predjelo', 567);
insert into Dishes (Name, Category, Calories) values ('Carrot Soup', 'Predjelo', 811);
insert into Dishes (Name, Category, Calories) values ('Avocado Toast', 'Desert', 89);
insert into Dishes (Name, Category, Calories) values ('Smoked Salmon Bagel', 'Glavno jelo', 792);
insert into Dishes (Name, Category, Calories) values ('Thai Red Curry', 'Glavno jelo', 392);
insert into Dishes (Name, Category, Calories) values ('Beef Sliders', 'Glavno jelo', 382);
insert into Dishes (Name, Category, Calories) values ('Fish Stew', 'Desert', 264);
insert into Dishes (Name, Category, Calories) values ('Zucchini Noodles', 'Predjelo', 321);
insert into Dishes (Name, Category, Calories) values ('Spaghetti Carbonara', 'Glavno jelo', 612);
insert into Dishes (Name, Category, Calories) values ('Roasted Lamb', 'Glavno jelo', 879);
insert into Dishes (Name, Category, Calories) values ('Caprese Sandwich', 'Glavno jelo', 883);
insert into Dishes (Name, Category, Calories) values ('Cajun Shrimp', 'Glavno jelo', 434);
insert into Dishes (Name, Category, Calories) values ('Baked Cod', 'Glavno jelo', 648);
insert into Dishes (Name, Category, Calories) values ('Black Bean Soup', 'Glavno jelo', 948);
insert into Dishes (Name, Category, Calories) values ('Steamed Mussels', 'Predjelo', 378);
insert into Dishes (Name, Category, Calories) values ('Pork Schnitzel Sandwich', 'Desert', 904);
insert into Dishes (Name, Category, Calories) values ('Apple Salad', 'Desert', 329);
insert into Dishes (Name, Category, Calories) values ('Salted Caramel Brownie', 'Predjelo', 664);
insert into Dishes (Name, Category, Calories) values ('Shrimp and Avocado Salad', 'Predjelo', 968);
insert into Dishes (Name, Category, Calories) values ('Honey Garlic Chicken', 'Glavno jelo', 934);
insert into Dishes (Name, Category, Calories) values ('Ratatouille', 'Desert', 267);
insert into Dishes (Name, Category, Calories) values ('Paneer Tikka', 'Desert', 965);
insert into Dishes (Name, Category, Calories) values ('Beef Burrito', 'Predjelo', 498);
insert into Dishes (Name, Category, Calories) values ('Roasted Turkey Sandwich', 'Desert', 186);
insert into Dishes (Name, Category, Calories) values ('Vegetable Pizza', 'Desert', 963);
insert into Dishes (Name, Category, Calories) values ('Grilled Tilapia', 'Desert', 111);
insert into Dishes (Name, Category, Calories) values ('Fish Soup', 'Predjelo', 75);
insert into Dishes (Name, Category, Calories) values ('Herb Roasted Chicken', 'Glavno jelo', 81);
insert into Dishes (Name, Category, Calories) values ('Grilled Chicken Salad', 'Desert', 552);
insert into Dishes (Name, Category, Calories) values ('Chicken Paella', 'Desert', 144);
insert into Dishes (Name, Category, Calories) values ('Duck Tacos', 'Desert', 244);
insert into Dishes (Name, Category, Calories) values ('Roast Veggie Salad', 'Desert', 719);
insert into Dishes (Name, Category, Calories) values ('Fish Platter', 'Desert', 685);
insert into Dishes (Name, Category, Calories) values ('Scallops with Lemon Butter', 'Glavno jelo', 232);
insert into Dishes (Name, Category, Calories) values ('Beef and Broccoli', 'Desert', 153);
insert into Dishes (Name, Category, Calories) values ('Chicken Kiev', 'Glavno jelo', 569);
insert into Dishes (Name, Category, Calories) values ('Veggie Noodles', 'Predjelo', 664);
insert into Dishes (Name, Category, Calories) values ('Grilled Veal Chops', 'Predjelo', 142);
insert into Dishes (Name, Category, Calories) values ('Thai Spring Rolls', 'Desert', 772);
insert into Dishes (Name, Category, Calories) values ('Grilled Bacon-Wrapped Shrimp', 'Predjelo', 973);
insert into Dishes (Name, Category, Calories) values ('Spicy Chicken Caesar Wrap', 'Glavno jelo', 384);
insert into Dishes (Name, Category, Calories) values ('Mushroom Risotto Balls', 'Predjelo', 708);
insert into Dishes (Name, Category, Calories) values ('Grilled Squid', 'Glavno jelo', 968);
insert into Dishes (Name, Category, Calories) values ('Chicken Tortilla Soup', 'Predjelo', 311);
insert into Dishes (Name, Category, Calories) values ('Pork and Rice', 'Predjelo', 334);
insert into Dishes (Name, Category, Calories) values ('Spinach and Ricotta Ravioli', 'Glavno jelo', 235);
insert into Dishes (Name, Category, Calories) values ('Smoked Trout Salad', 'Glavno jelo', 850);
insert into Dishes (Name, Category, Calories) values ('Fish Tacos with Slaw', 'Glavno jelo', 690);
insert into Dishes (Name, Category, Calories) values ('Chicken Parmesan Sub', 'Glavno jelo', 523);
insert into Dishes (Name, Category, Calories) values ('Grilled Sweet Potato', 'Desert', 662);
insert into Dishes (Name, Category, Calories) values ('Eggplant Caponata', 'Desert', 426);
insert into Dishes (Name, Category, Calories) values ('Chicken Shawarma Wrap', 'Glavno jelo', 727);
insert into Dishes (Name, Category, Calories) values ('Grilled Veal Cutlet', 'Predjelo', 143);
insert into Dishes (Name, Category, Calories) values ('Beef Pot Roast', 'Desert', 61);
insert into Dishes (Name, Category, Calories) values ('Sweet Chili Chicken', 'Desert', 117);
insert into Dishes (Name, Category, Calories) values ('Spaghetti with Shrimp', 'Desert', 567);
insert into Dishes (Name, Category, Calories) values ('Veggie Frittata', 'Predjelo', 898);
insert into Dishes (Name, Category, Calories) values ('Potato Salad', 'Predjelo', 318);
insert into Dishes (Name, Category, Calories) values ('Chicken in White Wine Sauce', 'Desert', 747);
insert into Dishes (Name, Category, Calories) values ('Beef Burrito Bowl', 'Glavno jelo', 846);
insert into Dishes (Name, Category, Calories) values ('Tuna Salad Sandwich', 'Desert', 130);
insert into Dishes (Name, Category, Calories) values ('Lobster Ravioli', 'Glavno jelo', 262);
insert into Dishes (Name, Category, Calories) values ('Beef Chili Fries', 'Glavno jelo', 250);
insert into Dishes (Name, Category, Calories) values ('Smoked Chicken Wings', 'Desert', 496);
insert into Dishes (Name, Category, Calories) values ('Tofu Pad Thai', 'Desert', 596);
insert into Dishes (Name, Category, Calories) values ('Shrimp and Spinach', 'Glavno jelo', 639);
insert into Dishes (Name, Category, Calories) values ('Salmon Cakes', 'Glavno jelo', 343);
insert into Dishes (Name, Category, Calories) values ('Chicken and Prawn Risotto', 'Glavno jelo', 145);
insert into Dishes (Name, Category, Calories) values ('Grilled Lamb Chops with Mint', 'Glavno jelo', 143);
insert into Dishes (Name, Category, Calories) values ('Shrimp Ramen', 'Desert', 406);
insert into Dishes (Name, Category, Calories) values ('Tofu and Vegetable Skewers', 'Desert', 348);
insert into Dishes (Name, Category, Calories) values ('Chicken Fricassée', 'Predjelo', 505);
insert into Dishes (Name, Category, Calories) values ('Mediterranean Salad', 'Desert', 893);
insert into Dishes (Name, Category, Calories) values ('Veggie Souvlaki', 'Glavno jelo', 190);
insert into Dishes (Name, Category, Calories) values ('Roasted Squash', 'Glavno jelo', 114);
insert into Dishes (Name, Category, Calories) values ('Spicy Lamb Tacos', 'Predjelo', 219);
insert into Dishes (Name, Category, Calories) values ('Grilled Mackerel', 'Glavno jelo', 374);
insert into Dishes (Name, Category, Calories) values ('Pork and Beans', 'Desert', 587);
insert into Dishes (Name, Category, Calories) values ('Ziti with Meatballs', 'Desert', 435);
insert into Dishes (Name, Category, Calories) values ('Bacon Wrapped Chicken', 'Predjelo', 642);
insert into Dishes (Name, Category, Calories) values ('Pappardelle with Pesto', 'Desert', 203);
insert into Dishes (Name, Category, Calories) values ('Crab Salad Sandwich', 'Glavno jelo', 610);
insert into Dishes (Name, Category, Calories) values ('Veggie Burger with Fries', 'Predjelo', 622);
insert into Dishes (Name, Category, Calories) values ('Chicken Nuggets with Fries', 'Desert', 408);
insert into Dishes (Name, Category, Calories) values ('Baked Eggplant Parmesan', 'Glavno jelo', 400);
insert into Dishes (Name, Category, Calories) values ('Chicken with Garlic Mashed Potatoes', 'Predjelo', 930);
insert into Dishes (Name, Category, Calories) values ('Grilled Squash', 'Desert', 461);
insert into Dishes (Name, Category, Calories) values ('Grilled Pork Chop with Apple Sauce', 'Glavno jelo', 962);
insert into Dishes (Name, Category, Calories) values ('Shrimp Stuffed Mushrooms', 'Predjelo', 934);
insert into Dishes (Name, Category, Calories) values ('Vegetable Pakoras', 'Predjelo', 835);
insert into Dishes (Name, Category, Calories) values ('Grilled Shrimp Caesar Salad', 'Desert', 255);
insert into Dishes (Name, Category, Calories) values ('Spinach and Artichoke Dip', 'Desert', 241);
insert into Dishes (Name, Category, Calories) values ('Mushroom and Spinach Quesadilla', 'Glavno jelo', 652);
insert into Dishes (Name, Category, Calories) values ('Grilled Oyster Mushrooms', 'Predjelo', 958);
insert into Dishes (Name, Category, Calories) values ('Carrot Cake', 'Predjelo', 999);
insert into Dishes (Name, Category, Calories) values ('Red Lentil Soup', 'Desert', 71);
insert into Dishes (Name, Category, Calories) values ('Roasted Brussel Sprouts', 'Glavno jelo', 445);
insert into Dishes (Name, Category, Calories) values ('Grilled Zucchini', 'Glavno jelo', 413);
insert into Dishes (Name, Category, Calories) values ('Fennel and Orange Salad', 'Desert', 924);
insert into Dishes (Name, Category, Calories) values ('Chicken with Peas and Carrots', 'Desert', 420);
insert into Dishes (Name, Category, Calories) values ('Poached Salmon', 'Glavno jelo', 932);
insert into Dishes (Name, Category, Calories) values ('Grilled Scallops with Mango Salsa', 'Predjelo', 98);
insert into Dishes (Name, Category, Calories) values ('Veggie Wrap', 'Predjelo', 833);
insert into Dishes (Name, Category, Calories) values ('Shrimp Salad Roll', 'Glavno jelo', 882);
insert into Dishes (Name, Category, Calories) values ('Pan-fried Sole', 'Glavno jelo', 887);
insert into Dishes (Name, Category, Calories) values ('Seared Salmon with Lemon', 'Glavno jelo', 68);
insert into Dishes (Name, Category, Calories) values ('Cornbread Muffins', 'Glavno jelo', 788);
insert into Dishes (Name, Category, Calories) values ('Beef Wellington Bites', 'Desert', 347);
insert into Dishes (Name, Category, Calories) values ('Cheeseburger', 'Predjelo', 172);
insert into Dishes (Name, Category, Calories) values ('Grilled Chicken Salad', 'Predjelo', 569);
insert into Dishes (Name, Category, Calories) values ('Margherita Pizza', 'Glavno jelo', 147);
insert into Dishes (Name, Category, Calories) values ('Caesar Salad', 'Glavno jelo', 499);
insert into Dishes (Name, Category, Calories) values ('Beef Wellington', 'Desert', 960);
insert into Dishes (Name, Category, Calories) values ('Spaghetti Bolognese', 'Glavno jelo', 954);
insert into Dishes (Name, Category, Calories) values ('Chicken Alfredo', 'Desert', 487);
insert into Dishes (Name, Category, Calories) values ('Fish Tacos', 'Glavno jelo', 774);
insert into Dishes (Name, Category, Calories) values ('Lamb Chops', 'Predjelo', 322);
insert into Dishes (Name, Category, Calories) values ('Mushroom Risotto', 'Glavno jelo', 233);
insert into Dishes (Name, Category, Calories) values ('Veggie Burger', 'Glavno jelo', 133);
insert into Dishes (Name, Category, Calories) values ('Chicken Parmesan', 'Desert', 323);
insert into Dishes (Name, Category, Calories) values ('Shrimp Scampi', 'Desert', 164);
insert into Dishes (Name, Category, Calories) values ('Rib-eye Steak', 'Predjelo', 292);
insert into Dishes (Name, Category, Calories) values ('Chicken Quesadilla', 'Glavno jelo', 460);
insert into Dishes (Name, Category, Calories) values ('Pad Thai', 'Desert', 780);
insert into Dishes (Name, Category, Calories) values ('Lasagna', 'Predjelo', 153);
insert into Dishes (Name, Category, Calories) values ('Stuffed Bell Peppers', 'Predjelo', 947);
insert into Dishes (Name, Category, Calories) values ('Peking Duck', 'Predjelo', 405);
insert into Dishes (Name, Category, Calories) values ('Fish and Chips', 'Glavno jelo', 663);
insert into Dishes (Name, Category, Calories) values ('Chicken Tikka Masala', 'Predjelo', 219);
insert into Dishes (Name, Category, Calories) values ('Pork Schnitzel', 'Desert', 608);
insert into Dishes (Name, Category, Calories) values ('Grilled Salmon', 'Predjelo', 621);
insert into Dishes (Name, Category, Calories) values ('Eggplant Parmesan', 'Predjelo', 713);
insert into Dishes (Name, Category, Calories) values ('Fettuccine Carbonara', 'Desert', 755);
insert into Dishes (Name, Category, Calories) values ('Beef Burritos', 'Desert', 654);
insert into Dishes (Name, Category, Calories) values ('Chicken Fried Rice', 'Glavno jelo', 790);
insert into Dishes (Name, Category, Calories) values ('Shrimp Tempura', 'Desert', 579);
insert into Dishes (Name, Category, Calories) values ('Duck Confit', 'Predjelo', 279);
insert into Dishes (Name, Category, Calories) values ('Roasted Vegetables', 'Glavno jelo', 79);
insert into Dishes (Name, Category, Calories) values ('Tuna Tartare', 'Glavno jelo', 342);
insert into Dishes (Name, Category, Calories) values ('Beef Stroganoff', 'Predjelo', 125);
insert into Dishes (Name, Category, Calories) values ('Clam Chowder', 'Glavno jelo', 668);
insert into Dishes (Name, Category, Calories) values ('Grilled Shrimp Skewers', 'Predjelo', 364);
insert into Dishes (Name, Category, Calories) values ('Sweet and Sour Chicken', 'Glavno jelo', 409);
insert into Dishes (Name, Category, Calories) values ('Chicken Wings', 'Predjelo', 118);
insert into Dishes (Name, Category, Calories) values ('Meatball Sub', 'Desert', 178);
insert into Dishes (Name, Category, Calories) values ('Veggie Pizza', 'Desert', 188);
insert into Dishes (Name, Category, Calories) values ('Crab Cakes', 'Glavno jelo', 599);
insert into Dishes (Name, Category, Calories) values ('Chicken Caesar Wrap', 'Desert', 961);
insert into Dishes (Name, Category, Calories) values ('Spicy Tuna Roll', 'Desert', 137);
insert into Dishes (Name, Category, Calories) values ('Pork Belly', 'Glavno jelo', 920);
insert into Dishes (Name, Category, Calories) values ('Beef Fajitas', 'Desert', 977);
insert into Dishes (Name, Category, Calories) values ('Prawn Cocktail', 'Glavno jelo', 323);
insert into Dishes (Name, Category, Calories) values ('Beef Ribs', 'Predjelo', 883);
insert into Dishes (Name, Category, Calories) values ('Mushroom Soup', 'Glavno jelo', 73);
insert into Dishes (Name, Category, Calories) values ('Grilled Vegetables', 'Desert', 240);
insert into Dishes (Name, Category, Calories) values ('Roasted Chicken', 'Desert', 60);
insert into Dishes (Name, Category, Calories) values ('Chili Con Carne', 'Predjelo', 693);
insert into Dishes (Name, Category, Calories) values ('Fish Curry', 'Desert', 559);
insert into Dishes (Name, Category, Calories) values ('BBQ Ribs', 'Glavno jelo', 102);
insert into Dishes (Name, Category, Calories) values ('Chicken Nuggets', 'Predjelo', 964);
insert into Dishes (Name, Category, Calories) values ('Paella', 'Predjelo', 873);
insert into Dishes (Name, Category, Calories) values ('Veal Marsala', 'Glavno jelo', 405);
insert into Dishes (Name, Category, Calories) values ('Beef Empanadas', 'Predjelo', 930);
insert into Dishes (Name, Category, Calories) values ('Garlic Bread', 'Desert', 628);
insert into Dishes (Name, Category, Calories) values ('Chicken and Waffles', 'Predjelo', 597);
insert into Dishes (Name, Category, Calories) values ('Beef Kebabs', 'Glavno jelo', 448);
insert into Dishes (Name, Category, Calories) values ('Lobster Roll', 'Desert', 53);
insert into Dishes (Name, Category, Calories) values ('Baked Ziti', 'Desert', 754);
insert into Dishes (Name, Category, Calories) values ('Beef Tacos', 'Predjelo', 931);
insert into Dishes (Name, Category, Calories) values ('Crab Legs', 'Desert', 942);
insert into Dishes (Name, Category, Calories) values ('Shrimp Po'' Boy', 'Predjelo', 414);
insert into Dishes (Name, Category, Calories) values ('Shrimp Ceviche', 'Glavno jelo', 59);
insert into Dishes (Name, Category, Calories) values ('Grilled Cheese Sandwich', 'Glavno jelo', 622);
insert into Dishes (Name, Category, Calories) values ('Nachos', 'Predjelo', 145);
insert into Dishes (Name, Category, Calories) values ('Beef Lasagna', 'Glavno jelo', 192);
insert into Dishes (Name, Category, Calories) values ('Chicken Souvlaki', 'Predjelo', 960);
insert into Dishes (Name, Category, Calories) values ('Pork Tenderloin', 'Predjelo', 377);
insert into Dishes (Name, Category, Calories) values ('Beef Skewers', 'Predjelo', 354);
insert into Dishes (Name, Category, Calories) values ('Chicken Satay', 'Glavno jelo', 905);
insert into Dishes (Name, Category, Calories) values ('Grilled Tuna', 'Glavno jelo', 990);
insert into Dishes (Name, Category, Calories) values ('Tuna Salad', 'Predjelo', 349);
insert into Dishes (Name, Category, Calories) values ('Roasted Pork', 'Predjelo', 353);
insert into Dishes (Name, Category, Calories) values ('Vegetable Stir Fry', 'Predjelo', 258);
insert into Dishes (Name, Category, Calories) values ('Grilled Octopus', 'Glavno jelo', 316);
insert into Dishes (Name, Category, Calories) values ('BBQ Pulled Pork', 'Desert', 698);
insert into Dishes (Name, Category, Calories) values ('Lamb Shank', 'Desert', 506);
insert into Dishes (Name, Category, Calories) values ('Crab Linguine', 'Glavno jelo', 881);
insert into Dishes (Name, Category, Calories) values ('Mushroom Tarts', 'Predjelo', 351);
insert into Dishes (Name, Category, Calories) values ('Broccoli and Cheese', 'Desert', 697);
insert into Dishes (Name, Category, Calories) values ('Thai Green Curry', 'Predjelo', 971);
insert into Dishes (Name, Category, Calories) values ('Grilled Veal', 'Desert', 770);
insert into Dishes (Name, Category, Calories) values ('Grilled Chicken Tenders', 'Predjelo', 302);
insert into Dishes (Name, Category, Calories) values ('Caprese Salad', 'Predjelo', 890);
insert into Dishes (Name, Category, Calories) values ('Beef Kofta', 'Predjelo', 98);
insert into Dishes (Name, Category, Calories) values ('Moussaka', 'Desert', 751);
insert into Dishes (Name, Category, Calories) values ('Seafood Paella', 'Glavno jelo', 805);
insert into Dishes (Name, Category, Calories) values ('Chicken Shawarma', 'Glavno jelo', 243);
insert into Dishes (Name, Category, Calories) values ('Chicken and Rice', 'Predjelo', 420);
insert into Dishes (Name, Category, Calories) values ('Grilled Trout', 'Glavno jelo', 381);
insert into Dishes (Name, Category, Calories) values ('Lobster Bisque', 'Predjelo', 966);
insert into Dishes (Name, Category, Calories) values ('Baked Salmon', 'Predjelo', 362);
insert into Dishes (Name, Category, Calories) values ('Spaghetti Aglio e Olio', 'Glavno jelo', 777);
insert into Dishes (Name, Category, Calories) values ('Crispy Chicken Sandwich', 'Predjelo', 238);
insert into Dishes (Name, Category, Calories) values ('Chili Dog', 'Glavno jelo', 801);
insert into Dishes (Name, Category, Calories) values ('French Toast', 'Desert', 339);
insert into Dishes (Name, Category, Calories) values ('Bacon-Wrapped Scallops', 'Glavno jelo', 349);
insert into Dishes (Name, Category, Calories) values ('Stuffed Mushrooms', 'Predjelo', 821);
insert into Dishes (Name, Category, Calories) values ('Egg Salad', 'Desert', 122);
insert into Dishes (Name, Category, Calories) values ('Gyro', 'Desert', 377);
insert into Dishes (Name, Category, Calories) values ('Grilled Pork Chops', 'Glavno jelo', 788);
insert into Dishes (Name, Category, Calories) values ('Philly Cheesesteak', 'Predjelo', 381);
insert into Dishes (Name, Category, Calories) values ('Chicken Tenders', 'Desert', 596);
insert into Dishes (Name, Category, Calories) values ('Tofu Stir Fry', 'Predjelo', 68);
insert into Dishes (Name, Category, Calories) values ('Shrimp Fried Rice', 'Predjelo', 697);
insert into Dishes (Name, Category, Calories) values ('Beef Empanada', 'Glavno jelo', 176);
insert into Dishes (Name, Category, Calories) values ('Grilled Lamb Kebabs', 'Desert', 252);
insert into Dishes (Name, Category, Calories) values ('Vegetable Samosas', 'Glavno jelo', 847);
insert into Dishes (Name, Category, Calories) values ('Pasta Primavera', 'Desert', 525);
insert into Dishes (Name, Category, Calories) values ('Sweet Potato Fries', 'Predjelo', 241);
insert into Dishes (Name, Category, Calories) values ('Croque Monsieur', 'Desert', 318);
insert into Dishes (Name, Category, Calories) values ('Grilled Fish', 'Predjelo', 285);
insert into Dishes (Name, Category, Calories) values ('Lamb Stew', 'Glavno jelo', 691);
insert into Dishes (Name, Category, Calories) values ('Beef Wellington', 'Glavno jelo', 754);
insert into Dishes (Name, Category, Calories) values ('Chicken Kiev', 'Glavno jelo', 845);
insert into Dishes (Name, Category, Calories) values ('Mozzarella Sticks', 'Desert', 936);
insert into Dishes (Name, Category, Calories) values ('Fish Tacos', 'Desert', 708);
insert into Dishes (Name, Category, Calories) values ('Eggplant Rollatini', 'Glavno jelo', 160);
insert into Dishes (Name, Category, Calories) values ('Beef Burrito Bowl', 'Glavno jelo', 283);
insert into Dishes (Name, Category, Calories) values ('Chicken Marsala', 'Predjelo', 434);
insert into Dishes (Name, Category, Calories) values ('Grilled Fish Tacos', 'Desert', 708);
insert into Dishes (Name, Category, Calories) values ('Lamb Biryani', 'Desert', 642);
insert into Dishes (Name, Category, Calories) values ('Spicy Chicken Wings', 'Predjelo', 375);
insert into Dishes (Name, Category, Calories) values ('Chicken Soup', 'Glavno jelo', 495);
insert into Dishes (Name, Category, Calories) values ('Shrimp Gumbo', 'Predjelo', 748);
insert into Dishes (Name, Category, Calories) values ('Baked Potato Soup', 'Desert', 981);
insert into Dishes (Name, Category, Calories) values ('Chili Cheese Fries', 'Glavno jelo', 466);
insert into Dishes (Name, Category, Calories) values ('Pasta Bolognese', 'Predjelo', 715);
insert into Dishes (Name, Category, Calories) values ('Chicken Burrito', 'Predjelo', 79);
insert into Dishes (Name, Category, Calories) values ('Steak Frites', 'Predjelo', 150);
insert into Dishes (Name, Category, Calories) values ('Pasta Carbonara', 'Desert', 941);
insert into Dishes (Name, Category, Calories) values ('Beef Steak', 'Desert', 475);
insert into Dishes (Name, Category, Calories) values ('Shrimp and Grits', 'Predjelo', 146);
insert into Dishes (Name, Category, Calories) values ('Egg Salad Sandwich', 'Glavno jelo', 640);
insert into Dishes (Name, Category, Calories) values ('Buffalo Wings', 'Glavno jelo', 942);
insert into Dishes (Name, Category, Calories) values ('Jambalaya', 'Predjelo', 158);
insert into Dishes (Name, Category, Calories) values ('Tofu Burger', 'Glavno jelo', 850);
insert into Dishes (Name, Category, Calories) values ('Fajita Bowl', 'Desert', 743);
insert into Dishes (Name, Category, Calories) values ('Prawn Risotto', 'Glavno jelo', 381);
