insert into Rating (RatingNum, Comment, DishId) values (1, 'Odličan okus, baš je bilo savršeno!', 205);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 41);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršen obrok, jako sam zadovoljan!', 326);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 291);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 85);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izuzetno ukusno, odličan balans okusa!', 459);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 97);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 70);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 341);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ukusno, ali bi volio da je bilo malo više začina.', 250);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 365);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo previše masno, ali ukusno.', 415);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 209);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Prvi put probam ovo jelo i jako mi se sviđa.', 91);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 334);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 467);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Odlično! Sve je bilo na visokom nivou.', 320);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Užitak za nepce, savršen obrok.', 376);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 19);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Savršena veličina porcije, baš ono što mi je trebalo.', 371);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 57);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 25);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Izvanredno! Jelo je bilo stvarno ukusno.', 418);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 474);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 76);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Usluga je bila super, a jelo je bilo fenomenalno.', 353);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 369);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Odlična tekstura, meso je bilo baš kako treba.', 97);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Užitak za nepce, okus se dugo zadržava.', 20);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 378);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 1);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 478);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Preporučujem ovo jelo, odličan odabir začina.', 399);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 54);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 422);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 51);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 225);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 277);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Izvrsno! Osim što bi povrće moglo biti malo svježije.', 75);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ovo je jelo bilo pravo iznenađenje, jako sam ugodno iznenađen.', 365);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Ukusno, ali malo previše začinjeno.', 58);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Previše je bilo umaka, ali jelo je bilo dobro.', 348);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odličan okus, baš je bilo savršeno!', 242);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 322);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Savršen obrok, jako sam zadovoljan!', 256);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 369);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 337);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Izuzetno ukusno, odličan balans okusa!', 287);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 148);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 336);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 102);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ukusno, ali bi volio da je bilo malo više začina.', 116);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 138);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo previše masno, ali ukusno.', 367);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 94);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Prvi put probam ovo jelo i jako mi se sviđa.', 370);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 465);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 258);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Odlično! Sve je bilo na visokom nivou.', 481);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Užitak za nepce, savršen obrok.', 189);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 387);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršena veličina porcije, baš ono što mi je trebalo.', 329);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 61);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 432);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izvanredno! Jelo je bilo stvarno ukusno.', 42);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 465);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 446);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Usluga je bila super, a jelo je bilo fenomenalno.', 112);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 440);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odlična tekstura, meso je bilo baš kako treba.', 175);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Užitak za nepce, okus se dugo zadržava.', 224);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 244);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 90);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 348);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Preporučujem ovo jelo, odličan odabir začina.', 79);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 410);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 140);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 119);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 276);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 296);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Izvrsno! Osim što bi povrće moglo biti malo svježije.', 352);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Ovo je jelo bilo pravo iznenađenje, jako sam ugodno iznenađen.', 372);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali malo previše začinjeno.', 377);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Previše je bilo umaka, ali jelo je bilo dobro.', 98);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Odličan okus, baš je bilo savršeno!', 32);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 105);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Savršen obrok, jako sam zadovoljan!', 443);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 111);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 161);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Izuzetno ukusno, odličan balans okusa!', 14);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 403);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 216);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 101);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Ukusno, ali bi volio da je bilo malo više začina.', 463);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 136);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jelo je bilo previše masno, ali ukusno.', 442);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 212);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Prvi put probam ovo jelo i jako mi se sviđa.', 435);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 331);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 97);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Odlično! Sve je bilo na visokom nivou.', 325);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Užitak za nepce, savršen obrok.', 308);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 247);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršena veličina porcije, baš ono što mi je trebalo.', 222);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 469);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 371);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Izvanredno! Jelo je bilo stvarno ukusno.', 148);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 86);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 128);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Usluga je bila super, a jelo je bilo fenomenalno.', 343);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 483);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Odlična tekstura, meso je bilo baš kako treba.', 390);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Užitak za nepce, okus se dugo zadržava.', 435);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 390);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 281);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 180);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Preporučujem ovo jelo, odličan odabir začina.', 243);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 351);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 131);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 474);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 5);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 268);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Izvrsno! Osim što bi povrće moglo biti malo svježije.', 273);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ovo je jelo bilo pravo iznenađenje, jako sam ugodno iznenađen.', 336);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Ukusno, ali malo previše začinjeno.', 447);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Previše je bilo umaka, ali jelo je bilo dobro.', 339);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odličan okus, baš je bilo savršeno!', 458);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 238);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Savršen obrok, jako sam zadovoljan!', 317);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 460);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 370);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Izuzetno ukusno, odličan balans okusa!', 137);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 270);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 267);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 426);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ukusno, ali bi volio da je bilo malo više začina.', 491);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 46);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo previše masno, ali ukusno.', 187);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 224);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Prvi put probam ovo jelo i jako mi se sviđa.', 218);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 312);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 214);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Odlično! Sve je bilo na visokom nivou.', 358);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Užitak za nepce, savršen obrok.', 344);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 294);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Savršena veličina porcije, baš ono što mi je trebalo.', 411);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 466);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 366);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Izvanredno! Jelo je bilo stvarno ukusno.', 168);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 92);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 78);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Usluga je bila super, a jelo je bilo fenomenalno.', 62);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 403);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Odlična tekstura, meso je bilo baš kako treba.', 205);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Užitak za nepce, okus se dugo zadržava.', 351);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 429);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 44);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 4);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Preporučujem ovo jelo, odličan odabir začina.', 70);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 185);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 31);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 476);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 237);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 65);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Izvrsno! Osim što bi povrće moglo biti malo svježije.', 339);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ovo je jelo bilo pravo iznenađenje, jako sam ugodno iznenađen.', 161);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ukusno, ali malo previše začinjeno.', 484);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Previše je bilo umaka, ali jelo je bilo dobro.', 455);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odličan okus, baš je bilo savršeno!', 105);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 190);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršen obrok, jako sam zadovoljan!', 13);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 463);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 374);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izuzetno ukusno, odličan balans okusa!', 431);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 239);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 378);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 409);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ukusno, ali bi volio da je bilo malo više začina.', 438);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 408);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jelo je bilo previše masno, ali ukusno.', 410);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 446);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Prvi put probam ovo jelo i jako mi se sviđa.', 59);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 28);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 344);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Odlično! Sve je bilo na visokom nivou.', 459);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Užitak za nepce, savršen obrok.', 443);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 186);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Savršena veličina porcije, baš ono što mi je trebalo.', 406);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 405);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 465);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izvanredno! Jelo je bilo stvarno ukusno.', 72);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 7);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 145);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Usluga je bila super, a jelo je bilo fenomenalno.', 129);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 13);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odlična tekstura, meso je bilo baš kako treba.', 2);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Užitak za nepce, okus se dugo zadržava.', 275);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 138);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 160);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 143);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Preporučujem ovo jelo, odličan odabir začina.', 114);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 35);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 124);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 289);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 480);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 463);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izvrsno! Osim što bi povrće moglo biti malo svježije.', 197);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ovo je jelo bilo pravo iznenađenje, jako sam ugodno iznenađen.', 343);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali malo previše začinjeno.', 110);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Previše je bilo umaka, ali jelo je bilo dobro.', 42);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Odličan okus, baš je bilo savršeno!', 356);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 206);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršen obrok, jako sam zadovoljan!', 412);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 399);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 131);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Izuzetno ukusno, odličan balans okusa!', 331);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 55);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 22);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 224);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Ukusno, ali bi volio da je bilo malo više začina.', 260);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 78);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo previše masno, ali ukusno.', 344);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 330);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Prvi put probam ovo jelo i jako mi se sviđa.', 468);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 96);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 195);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odlično! Sve je bilo na visokom nivou.', 309);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Užitak za nepce, savršen obrok.', 293);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 142);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Savršena veličina porcije, baš ono što mi je trebalo.', 257);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 412);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 107);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Izvanredno! Jelo je bilo stvarno ukusno.', 291);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 35);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 174);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Usluga je bila super, a jelo je bilo fenomenalno.', 219);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 454);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Odlična tekstura, meso je bilo baš kako treba.', 142);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Užitak za nepce, okus se dugo zadržava.', 83);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 425);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 63);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 440);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Preporučujem ovo jelo, odličan odabir začina.', 433);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 423);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 175);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 189);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 22);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 257);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izvrsno! Osim što bi povrće moglo biti malo svježije.', 45);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ovo je jelo bilo pravo iznenađenje, jako sam ugodno iznenađen.', 245);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali malo previše začinjeno.', 395);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Previše je bilo umaka, ali jelo je bilo dobro.', 458);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odličan okus, baš je bilo savršeno!', 310);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 175);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Savršen obrok, jako sam zadovoljan!', 474);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 204);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 488);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Izuzetno ukusno, odličan balans okusa!', 327);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 160);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 117);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 214);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ukusno, ali bi volio da je bilo malo više začina.', 185);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 282);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo previše masno, ali ukusno.', 103);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 64);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Prvi put probam ovo jelo i jako mi se sviđa.', 234);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 20);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 396);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odlično! Sve je bilo na visokom nivou.', 485);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Užitak za nepce, savršen obrok.', 262);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 196);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršena veličina porcije, baš ono što mi je trebalo.', 57);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 486);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 10);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izvanredno! Jelo je bilo stvarno ukusno.', 461);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 466);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 432);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Usluga je bila super, a jelo je bilo fenomenalno.', 38);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 388);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odlična tekstura, meso je bilo baš kako treba.', 220);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Užitak za nepce, okus se dugo zadržava.', 218);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 455);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 304);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 246);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Preporučujem ovo jelo, odličan odabir začina.', 356);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 492);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 315);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 153);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 111);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 244);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Izvrsno! Osim što bi povrće moglo biti malo svježije.', 24);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ovo je jelo bilo pravo iznenađenje, jako sam ugodno iznenađen.', 61);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Ukusno, ali malo previše začinjeno.', 473);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Previše je bilo umaka, ali jelo je bilo dobro.', 499);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odličan okus, baš je bilo savršeno!', 318);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 280);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Savršen obrok, jako sam zadovoljan!', 358);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 93);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 498);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izuzetno ukusno, odličan balans okusa!', 151);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 370);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 400);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 297);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Ukusno, ali bi volio da je bilo malo više začina.', 163);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 190);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo previše masno, ali ukusno.', 323);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 458);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Prvi put probam ovo jelo i jako mi se sviđa.', 42);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 292);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 498);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Odlično! Sve je bilo na visokom nivou.', 278);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Užitak za nepce, savršen obrok.', 463);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 129);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Savršena veličina porcije, baš ono što mi je trebalo.', 377);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 180);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 165);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Izvanredno! Jelo je bilo stvarno ukusno.', 70);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 157);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 411);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Usluga je bila super, a jelo je bilo fenomenalno.', 283);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 451);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Odlična tekstura, meso je bilo baš kako treba.', 482);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Užitak za nepce, okus se dugo zadržava.', 372);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 11);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 324);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 187);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Preporučujem ovo jelo, odličan odabir začina.', 23);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 426);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 298);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 8);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 146);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 91);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izvrsno! Osim što bi povrće moglo biti malo svježije.', 396);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ovo je jelo bilo pravo iznenađenje, jako sam ugodno iznenađen.', 355);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Ukusno, ali malo previše začinjeno.', 74);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Previše je bilo umaka, ali jelo je bilo dobro.', 213);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Odličan okus, baš je bilo savršeno!', 321);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 155);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Savršen obrok, jako sam zadovoljan!', 297);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 78);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 471);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Izuzetno ukusno, odličan balans okusa!', 147);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 105);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 232);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 149);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ukusno, ali bi volio da je bilo malo više začina.', 36);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 322);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo previše masno, ali ukusno.', 89);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 288);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Prvi put probam ovo jelo i jako mi se sviđa.', 256);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 492);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 484);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Odlično! Sve je bilo na visokom nivou.', 302);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Užitak za nepce, savršen obrok.', 422);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 396);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Savršena veličina porcije, baš ono što mi je trebalo.', 277);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 75);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 329);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Izvanredno! Jelo je bilo stvarno ukusno.', 491);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 43);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 449);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Usluga je bila super, a jelo je bilo fenomenalno.', 324);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 63);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Odlična tekstura, meso je bilo baš kako treba.', 82);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Užitak za nepce, okus se dugo zadržava.', 414);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 134);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 368);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 238);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Preporučujem ovo jelo, odličan odabir začina.', 46);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 106);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 340);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 412);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 232);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 74);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Izvrsno! Osim što bi povrće moglo biti malo svježije.', 196);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Ovo je jelo bilo pravo iznenađenje, jako sam ugodno iznenađen.', 355);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Ukusno, ali malo previše začinjeno.', 487);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Previše je bilo umaka, ali jelo je bilo dobro.', 374);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Odličan okus, baš je bilo savršeno!', 41);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 442);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Savršen obrok, jako sam zadovoljan!', 353);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 217);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 180);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izuzetno ukusno, odličan balans okusa!', 476);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 416);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 145);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 37);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ukusno, ali bi volio da je bilo malo više začina.', 442);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 456);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jelo je bilo previše masno, ali ukusno.', 115);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 482);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Prvi put probam ovo jelo i jako mi se sviđa.', 417);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 82);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 447);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odlično! Sve je bilo na visokom nivou.', 455);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Užitak za nepce, savršen obrok.', 184);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 285);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Savršena veličina porcije, baš ono što mi je trebalo.', 263);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 497);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 494);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izvanredno! Jelo je bilo stvarno ukusno.', 35);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 432);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 91);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Usluga je bila super, a jelo je bilo fenomenalno.', 442);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 176);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Odlična tekstura, meso je bilo baš kako treba.', 216);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Užitak za nepce, okus se dugo zadržava.', 470);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 14);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 23);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 240);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Preporučujem ovo jelo, odličan odabir začina.', 234);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 130);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 301);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 20);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 362);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 130);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izvrsno! Osim što bi povrće moglo biti malo svježije.', 63);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Ovo je jelo bilo pravo iznenađenje, jako sam ugodno iznenađen.', 73);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Ukusno, ali malo previše začinjeno.', 197);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Previše je bilo umaka, ali jelo je bilo dobro.', 86);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Odličan okus, baš je bilo savršeno!', 122);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 93);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Savršen obrok, jako sam zadovoljan!', 299);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 364);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 160);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Izuzetno ukusno, odličan balans okusa!', 123);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 249);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 289);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 253);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Ukusno, ali bi volio da je bilo malo više začina.', 450);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 44);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Jelo je bilo previše masno, ali ukusno.', 139);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 499);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Prvi put probam ovo jelo i jako mi se sviđa.', 257);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 55);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 179);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Odlično! Sve je bilo na visokom nivou.', 50);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Užitak za nepce, savršen obrok.', 304);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 358);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Savršena veličina porcije, baš ono što mi je trebalo.', 295);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 303);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 224);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izvanredno! Jelo je bilo stvarno ukusno.', 245);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 54);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 307);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Usluga je bila super, a jelo je bilo fenomenalno.', 149);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 242);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odlična tekstura, meso je bilo baš kako treba.', 231);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Užitak za nepce, okus se dugo zadržava.', 184);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 336);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 9);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 170);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Preporučujem ovo jelo, odličan odabir začina.', 461);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 92);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 329);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 114);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 155);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 427);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Izvrsno! Osim što bi povrće moglo biti malo svježije.', 263);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Ovo je jelo bilo pravo iznenađenje, jako sam ugodno iznenađen.', 172);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Ukusno, ali malo previše začinjeno.', 368);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Previše je bilo umaka, ali jelo je bilo dobro.', 112);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Odličan okus, baš je bilo savršeno!', 42);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Meso je bilo malo suho, ali ostatak jela je bio izvrstan.', 184);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Savršen obrok, jako sam zadovoljan!', 68);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Previše začina za moj ukus, ali jelo je bilo dobro.', 434);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Jelo je bilo previše slano za moj ukus, ali ukusi su individualni.', 177);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Izuzetno ukusno, odličan balans okusa!', 387);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jednostavno savršeno, sve je bilo u ravnoteži.', 110);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo previše začinjeno, ali sveukupno dobro.', 127);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Bilo je puno mesa, no povrće je bilo malo prekuhano.', 149);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali bi volio da je bilo malo više začina.', 187);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršena kombinacija okusa, uživao sam u svakom zalogaju.', 410);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo previše masno, ali ukusno.', 152);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Meso je bilo mekano i sočno, povrće je bilo svježe.', 331);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Prvi put probam ovo jelo i jako mi se sviđa.', 128);
insert into Rating (RatingNum, Comment, DishId) values (5, 'Ne mogu se odlučiti što mi se više svidjelo, jelo je bilo fantastično.', 459);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali mislim da bi malo manje soli poboljšalo okus.', 217);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Odlično! Sve je bilo na visokom nivou.', 17);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Užitak za nepce, savršen obrok.', 98);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Preporučam ovo jelo svakome tko voli bogate okuse.', 115);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Savršena veličina porcije, baš ono što mi je trebalo.', 223);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Meso je bilo malo prekuhano, ali sve ostalo je bilo odlično.', 294);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Sviđa mi se ovo jelo, ali mislim da bi moglo biti malo manje začinjeno.', 244);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Izvanredno! Jelo je bilo stvarno ukusno.', 496);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Vrlo zadovoljni, a desert je bio savršen završetak obroka.', 5);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Fantastičan obrok, zaslužuje svaku pohvalu!', 389);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Usluga je bila super, a jelo je bilo fenomenalno.', 107);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jelo je bilo jako bogato okusima, stvarno sam uživao.', 413);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Odlična tekstura, meso je bilo baš kako treba.', 467);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Užitak za nepce, okus se dugo zadržava.', 410);
insert into Rating (RatingNum, Comment, DishId) values (1, 'Obrok je bio fantastičan, sve je bilo savršeno pripremljeno.', 383);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Sviđa mi se ovo jelo, ali sljedeći put bih volio više povrća.', 178);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Bilo je previše začinjeno za moj ukus, ali sveukupno dobro.', 354);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Preporučujem ovo jelo, odličan odabir začina.', 32);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Meso je bilo ukusno, ali povrće mi se činilo previše kuhano.', 458);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Ukusno, ali možda malo više povrća ne bi škodilo.', 331);
insert into Rating (RatingNum, Comment, DishId) values (2, 'Jelo je bilo savršeno začinjeno, prava harmonija okusa.', 313);
insert into Rating (RatingNum, Comment, DishId) values (3, 'Jako mi se sviđa ovo jelo, ponovo bih ga naručio.', 361);
insert into Rating (RatingNum, Comment, DishId) values (4, 'Poboljšanja nisu potrebna, bilo je baš kako treba!', 409);
