insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Chevap', 'Slavonski Brod', 40, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Porcelliono', 'Čakovec', 17, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Podion', 'Karlovac', 7, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Graso', 'Dubrovnik', 48, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Luminara', 'Sisak', 14, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Zaffiro', 'Rijeka', 36, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Tavolo Verde', 'Varaždin', 27, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Bellavista', 'Pula', 31, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria Romana', 'Rijeka', 49, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Fiorentina', 'Rijeka', 17, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('El Bosco', 'Vinkovci', 9, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Pescatore', 'Zagreb', 39, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Pergola', 'Dubrovnik', 34, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Mare', 'Zagreb', 44, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Vino e Cucina', 'Rijeka', 3, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Tavola', 'Čakovec', 47, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cortile', 'Čakovec', 19, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Salotto', 'Sisak', 45, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolce Vita', 'Čakovec', 48, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Osteria del Sole', 'Vinkovci', 15, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Cucina di Nonna', 'Split', 50, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Forno', 'Slavonski Brod', 48, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Mamma Mia', 'Zadar', 45, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Saporito', 'Šibenik', 9, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Osteria Bella', 'Karlovac', 26, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria', 'Vukovar', 31, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Gusto e Vino', 'Čakovec', 15, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Vento d''Italia', 'Dubrovnik', 38, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto', 'Sisak', 19, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Baccus', 'Sisak', 19, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Rocca', 'Vukovar', 23, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Locanda', 'Zagreb', 13, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Sapori di Casa', 'Slavonski Brod', 23, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Via Roma', 'Vukovar', 50, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Piazza', 'Sisak', 14, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Albero d''Oro', 'Varaždin', 22, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Pescatore', 'Zagreb', 22, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Zafferano', 'Karlovac', 49, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria di Mare', 'Slavonski Brod', 49, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Angolo del Gusto', 'Pula', 17, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino', 'Varaždin', 14, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Bella Napoli', 'Rijeka', 41, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Stazione', 'Osijek', 5, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante dei Fiori', 'Šibenik', 38, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Mediterraneo', 'Karlovac', 39, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Serenata', 'Rijeka', 12, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Mamma', 'Zagreb', 13, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Fiore', 'Dubrovnik', 35, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Sotto le Stelle', 'Sisak', 6, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Villa Verde', 'Zagreb', 46, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Cielo Blu', 'Zagreb', 33, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Mare', 'Pula', 49, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Costa', 'Vinkovci', 42, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Bella Cucina', 'Karlovac', 48, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Mistral', 'Rijeka', 19, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore', 'Šibenik', 21, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Traviata', 'Rijeka', 44, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Finestra sul Mare', 'Pula', 43, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Girasole', 'Vukovar', 5, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Taverna', 'Rijeka', 38, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Pappagallo', 'Vukovar', 3, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Perla', 'Sisak', 19, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Fontana', 'Vukovar', 32, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Pino', 'Šibenik', 44, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Oasi del Gusto', 'Karlovac', 4, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Osteria', 'Sisak', 22, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello', 'Split', 8, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia', 'Zagreb', 16, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Fuoco e Vino', 'Čakovec', 12, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Le Terrazze', 'Pula', 15, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cielo', 'Zagreb', 35, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Casa del Mare', 'Zadar', 18, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolce Alleanza', 'Osijek', 35, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cuoco Felice', 'Split', 41, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Arco', 'Rijeka', 34, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria da Mario', 'Slavonski Brod', 5, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Cucina della Nonna', 'Dubrovnik', 42, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Villa della Luna', 'Vukovar', 38, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Al Fresco', 'Vinkovci', 39, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante d''Autore', 'Pula', 19, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Fiore di Mare', 'Karlovac', 7, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Palco', 'Karlovac', 10, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Griglia', 'Šibenik', 33, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Salento', 'Vinkovci', 1, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino Segreto', 'Vinkovci', 49, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Oasi Verde', 'Split', 16, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Faro', 'Sisak', 6, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Zenzero', 'Rijeka', 7, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Osteria Nuova', 'Šibenik', 46, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Sapore di Mare', 'Karlovac', 40, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Costa Azzurra', 'Split', 8, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Pasticceria del Viale', 'Vukovar', 24, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Galleria', 'Zadar', 36, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Antico', 'Varaždin', 26, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Mare Nostrum', 'Sisak', 32, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Tavernetta', 'Slavonski Brod', 40, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Lago', 'Osijek', 13, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Cucina di Vino', 'Čakovec', 2, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Pergolato', 'Zagreb', 39, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Fiamma', 'Pula', 29, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Casa del Vino', 'Slavonski Brod', 20, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Quinto Elemento', 'Čakovec', 49, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Marinella', 'Rijeka', 44, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Mia Tavola', 'Dubrovnik', 46, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cavallino', 'Čakovec', 12, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Refugio', 'Split', 23, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria Sorrento', 'Karlovac', 14, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Piatto del Giorno', 'Varaždin', 42, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Cuore di Cucina', 'Split', 17, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sogno', 'Pula', 28, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto della Vita', 'Slavonski Brod', 32, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Vela', 'Slavonski Brod', 32, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria Semplice', 'Šibenik', 21, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Piazzetta', 'Slavonski Brod', 13, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Parco', 'Šibenik', 34, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Verde', 'Čakovec', 47, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria del Borgo', 'Rijeka', 28, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Storia', 'Dubrovnik', 44, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Tramonto', 'Šibenik', 17, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Cascina', 'Split', 48, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Cucina Allegra', 'Vinkovci', 14, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Tramonto Rosso', 'Rijeka', 16, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Osteria Sorrentina', 'Čakovec', 49, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello di Vino', 'Pula', 29, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Vigna', 'Rijeka', 48, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Sapore di Bosco', 'Rijeka', 16, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria La Collina', 'Zagreb', 48, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Bosco Incantato', 'Slavonski Brod', 31, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Tesoro', 'Čakovec', 42, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria Il Cielo', 'Zagreb', 25, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Mare Blu', 'Varaždin', 9, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Tavola d''Oro', 'Karlovac', 50, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Pescatore Blu', 'Vukovar', 28, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante dei Sogni', 'Šibenik', 34, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Luna Piena', 'Zadar', 18, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Armonia', 'Čakovec', 34, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino d''Inverno', 'Sisak', 11, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello Blu', 'Osijek', 39, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Fortezza', 'Vukovar', 28, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Girasole', 'Rijeka', 38, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Villa dei Fiori', 'Varaždin', 40, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Torre', 'Pula', 5, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Buon Sapore', 'Dubrovnik', 50, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante delle Stelle', 'Pula', 37, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria al Vento', 'Sisak', 26, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolce Vita', 'Vinkovci', 41, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Piazza del Vino', 'Čakovec', 40, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Taverna del Mare', 'Vukovar', 34, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Mare e la Terra', 'Zagreb', 29, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore del Sole', 'Vukovar', 8, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria di Campagna', 'Sisak', 29, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria del Lago', 'Pula', 32, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Vino e la Cucina', 'Slavonski Brod', 41, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia Azzurra', 'Pula', 26, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolce Aria', 'Split', 19, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello del Vino', 'Slavonski Brod', 3, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Corte', 'Karlovac', 10, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria dei Nonni', 'Vukovar', 34, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino della Nonna', 'Osijek', 29, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Villa di Mare', 'Karlovac', 49, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Zagara', 'Zadar', 50, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Corte del Sole', 'Karlovac', 17, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante La Luna', 'Karlovac', 12, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Città del Gusto', 'Varaždin', 6, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolce Casa', 'Split', 45, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto del Vino', 'Dubrovnik', 42, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Ristorante del Mare', 'Zadar', 38, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baracca', 'Varaždin', 28, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cielo Blu', 'Split', 1, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria di Mare e Vino', 'Dubrovnik', 50, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante La Spiaggia', 'Zadar', 29, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Girasole d''Oro', 'Split', 4, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Stanza del Vino', 'Karlovac', 41, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Ristorante Verde', 'Dubrovnik', 10, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Torre del Gusto', 'Vukovar', 30, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria L''Isola', 'Šibenik', 42, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria del Vento', 'Karlovac', 35, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Bacio del Mare', 'Rijeka', 27, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Cucina di Pepe', 'Zadar', 32, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino della Taverna', 'Zagreb', 30, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Vino di Casa', 'Zagreb', 26, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Locanda dei Sapori', 'Zadar', 35, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Perla del Mare', 'Split', 26, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cuore del Gusto', 'Zadar', 25, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante da Vinci', 'Vukovar', 21, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Finestra del Vino', 'Pula', 6, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Rifugio dei Sapori', 'Dubrovnik', 33, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Corte del Mare', 'Karlovac', 48, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Cucina del Bosco', 'Dubrovnik', 43, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria da Leonardo', 'Split', 33, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino di Ercole', 'Vinkovci', 50, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia Verde', 'Osijek', 43, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria dei Fiori', 'Vukovar', 28, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria del Bosco', 'Karlovac', 40, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Casa di Nonna', 'Dubrovnik', 18, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto dell''Isola', 'Varaždin', 14, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore del Giardino', 'Vukovar', 19, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Terrazza sul Mare', 'Split', 24, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Ristorante dei Fiori', 'Varaždin', 20, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolcezza del Mare', 'Zadar', 29, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto dei Sogni', 'Zadar', 14, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Ristorante di Sorrento', 'Dubrovnik', 42, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria del Vecchio Borgo', 'Rijeka', 22, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Taverna del Bosco', 'Zadar', 43, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore del Vino', 'Sisak', 32, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia del Gusto', 'Split', 5, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria del Vecchio Castello', 'Dubrovnik', 20, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto dell''Amore', 'Vukovar', 2, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria della Vigna', 'Zagreb', 19, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello del Sole', 'Čakovec', 32, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Taverna di Leonardo', 'Vukovar', 24, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto dell''Oceano', 'Vinkovci', 49, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria del Parco', 'Zagreb', 46, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Stanza del Mare', 'Zagreb', 9, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Girasole del Vino', 'Vukovar', 40, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Villa dei Fiori', 'Split', 5, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia d''Oro', 'Varaždin', 21, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello della Luna', 'Pula', 45, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria dei Sogni', 'Zagreb', 38, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino dell''Isola', 'Šibenik', 50, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Tavola del Borgo', 'Dubrovnik', 8, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Rifugio della Vigna', 'Dubrovnik', 17, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria d''Oro', 'Zadar', 20, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore del Sole', 'Pula', 14, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Casa del Parco', 'Čakovec', 7, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Torre dei Sapori', 'Zadar', 10, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria dei Vigneti', 'Karlovac', 40, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello della Tavola', 'Šibenik', 26, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino del Sole', 'Rijeka', 18, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria di Sorrento', 'Zadar', 23, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello del Gusto', 'Osijek', 32, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Locanda del Mare', 'Dubrovnik', 18, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria della Luna', 'Osijek', 24, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino dei Sogni', 'Rijeka', 15, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia del Vino', 'Vinkovci', 26, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria del Mare', 'Šibenik', 28, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Casa del Gusto', 'Šibenik', 38, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore della Luna', 'Osijek', 41, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria dei Mare', 'Šibenik', 33, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Ristorante del Gusto', 'Sisak', 46, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Piazza di Leonardo', 'Čakovec', 37, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Taverna delle Stelle', 'Šibenik', 24, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Vino della Trattoria', 'Pula', 49, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Bella Trattoria', 'Sisak', 45, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Rifugio del Mare', 'Pula', 48, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria della Tavola', 'Sisak', 50, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Terra del Gusto', 'Čakovec', 23, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Girasole del Vino', 'Šibenik', 5, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Chevap', 'Karlovac', 48, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Porcelliono', 'Karlovac', 50, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Podion', 'Šibenik', 49, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Graso', 'Varaždin', 6, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Luminara', 'Pula', 16, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Zaffiro', 'Vinkovci', 31, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Tavolo Verde', 'Zagreb', 2, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Bellavista', 'Slavonski Brod', 16, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria Romana', 'Vinkovci', 8, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Fiorentina', 'Sisak', 21, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('El Bosco', 'Varaždin', 26, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Pescatore', 'Šibenik', 10, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Pergola', 'Zadar', 31, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Mare', 'Sisak', 35, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Vino e Cucina', 'Karlovac', 31, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Tavola', 'Karlovac', 39, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cortile', 'Split', 18, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Salotto', 'Split', 6, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolce Vita', 'Sisak', 39, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Osteria del Sole', 'Vinkovci', 41, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Cucina di Nonna', 'Vinkovci', 45, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Forno', 'Slavonski Brod', 17, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Mamma Mia', 'Osijek', 28, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Saporito', 'Varaždin', 10, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Osteria Bella', 'Slavonski Brod', 33, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria', 'Osijek', 37, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Gusto e Vino', 'Slavonski Brod', 2, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Vento d''Italia', 'Karlovac', 36, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto', 'Sisak', 50, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Baccus', 'Zadar', 2, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Rocca', 'Dubrovnik', 16, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Locanda', 'Zagreb', 21, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Sapori di Casa', 'Vukovar', 24, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Via Roma', 'Split', 27, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Piazza', 'Slavonski Brod', 5, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Albero d''Oro', 'Sisak', 47, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Pescatore', 'Osijek', 2, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Zafferano', 'Pula', 36, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria di Mare', 'Šibenik', 27, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Angolo del Gusto', 'Karlovac', 19, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino', 'Rijeka', 7, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Bella Napoli', 'Osijek', 40, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Stazione', 'Zadar', 19, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante dei Fiori', 'Dubrovnik', 27, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Mediterraneo', 'Pula', 20, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Serenata', 'Zagreb', 10, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Mamma', 'Čakovec', 6, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Fiore', 'Slavonski Brod', 39, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Sotto le Stelle', 'Sisak', 12, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Villa Verde', 'Varaždin', 48, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Cielo Blu', 'Rijeka', 36, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Mare', 'Pula', 47, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Costa', 'Varaždin', 2, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Bella Cucina', 'Zadar', 36, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Mistral', 'Zagreb', 40, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore', 'Osijek', 2, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Traviata', 'Rijeka', 48, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Finestra sul Mare', 'Split', 23, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Girasole', 'Sisak', 45, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Taverna', 'Karlovac', 27, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Pappagallo', 'Karlovac', 39, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Perla', 'Slavonski Brod', 22, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Fontana', 'Vinkovci', 31, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Pino', 'Varaždin', 30, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Oasi del Gusto', 'Vinkovci', 16, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Osteria', 'Šibenik', 21, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello', 'Karlovac', 15, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia', 'Šibenik', 9, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Fuoco e Vino', 'Šibenik', 32, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Le Terrazze', 'Split', 15, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cielo', 'Vukovar', 5, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Casa del Mare', 'Varaždin', 4, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolce Alleanza', 'Čakovec', 49, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cuoco Felice', 'Zagreb', 15, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Arco', 'Zadar', 50, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria da Mario', 'Slavonski Brod', 4, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Cucina della Nonna', 'Rijeka', 33, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Villa della Luna', 'Slavonski Brod', 34, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Al Fresco', 'Rijeka', 25, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante d''Autore', 'Pula', 30, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Fiore di Mare', 'Split', 25, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Palco', 'Šibenik', 9, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Griglia', 'Zagreb', 30, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Salento', 'Šibenik', 35, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino Segreto', 'Varaždin', 25, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Oasi Verde', 'Zadar', 3, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Faro', 'Sisak', 42, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Zenzero', 'Šibenik', 30, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Osteria Nuova', 'Čakovec', 5, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Sapore di Mare', 'Sisak', 17, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Costa Azzurra', 'Dubrovnik', 24, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Pasticceria del Viale', 'Vinkovci', 14, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Galleria', 'Dubrovnik', 2, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Antico', 'Slavonski Brod', 49, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Mare Nostrum', 'Dubrovnik', 7, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Tavernetta', 'Dubrovnik', 39, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Lago', 'Varaždin', 21, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Cucina di Vino', 'Vukovar', 10, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Pergolato', 'Pula', 47, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Fiamma', 'Šibenik', 23, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Casa del Vino', 'Slavonski Brod', 43, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Quinto Elemento', 'Zagreb', 45, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Marinella', 'Slavonski Brod', 18, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Mia Tavola', 'Čakovec', 45, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cavallino', 'Dubrovnik', 7, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Refugio', 'Rijeka', 21, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria Sorrento', 'Zadar', 2, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Piatto del Giorno', 'Dubrovnik', 48, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Cuore di Cucina', 'Pula', 18, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sogno', 'Varaždin', 24, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto della Vita', 'Čakovec', 48, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Vela', 'Zadar', 44, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria Semplice', 'Osijek', 39, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Piazzetta', 'Vinkovci', 26, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Parco', 'Karlovac', 31, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Verde', 'Vukovar', 39, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria del Borgo', 'Zagreb', 33, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Storia', 'Split', 7, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Tramonto', 'Zagreb', 38, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Cascina', 'Split', 8, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Cucina Allegra', 'Vukovar', 41, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Tramonto Rosso', 'Dubrovnik', 2, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Osteria Sorrentina', 'Sisak', 2, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello di Vino', 'Split', 31, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Vigna', 'Vinkovci', 35, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Sapore di Bosco', 'Karlovac', 3, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria La Collina', 'Zagreb', 39, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Bosco Incantato', 'Varaždin', 16, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Tesoro', 'Zadar', 46, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria Il Cielo', 'Zadar', 7, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Mare Blu', 'Vinkovci', 47, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Tavola d''Oro', 'Vukovar', 11, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Pescatore Blu', 'Pula', 9, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante dei Sogni', 'Zagreb', 29, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Luna Piena', 'Šibenik', 39, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('L''Armonia', 'Slavonski Brod', 2, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino d''Inverno', 'Vukovar', 19, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello Blu', 'Sisak', 17, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Fortezza', 'Pula', 18, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante Girasole', 'Rijeka', 29, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Villa dei Fiori', 'Pula', 15, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Torre', 'Sisak', 8, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Buon Sapore', 'Pula', 4, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante delle Stelle', 'Split', 17, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria al Vento', 'Karlovac', 41, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolce Vita', 'Osijek', 50, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Piazza del Vino', 'Zadar', 8, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Taverna del Mare', 'Dubrovnik', 16, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Mare e la Terra', 'Vukovar', 12, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore del Sole', 'Vinkovci', 15, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria di Campagna', 'Vukovar', 47, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria del Lago', 'Rijeka', 28, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Vino e la Cucina', 'Zagreb', 8, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia Azzurra', 'Sisak', 23, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolce Aria', 'Dubrovnik', 45, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello del Vino', 'Slavonski Brod', 47, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Corte', 'Vukovar', 28, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria dei Nonni', 'Zagreb', 41, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino della Nonna', 'Čakovec', 41, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Villa di Mare', 'Šibenik', 11, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Zagara', 'Vinkovci', 37, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Corte del Sole', 'Karlovac', 26, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante La Luna', 'Rijeka', 23, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Città del Gusto', 'Varaždin', 8, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolce Casa', 'Šibenik', 21, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto del Vino', 'Zagreb', 34, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Ristorante del Mare', 'Zagreb', 35, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baracca', 'Zadar', 48, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cielo Blu', 'Dubrovnik', 46, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria di Mare e Vino', 'Vukovar', 33, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante La Spiaggia', 'Dubrovnik', 48, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Girasole d''Oro', 'Šibenik', 13, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Stanza del Vino', 'Varaždin', 43, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Ristorante Verde', 'Dubrovnik', 12, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Torre del Gusto', 'Varaždin', 4, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria L''Isola', 'Rijeka', 39, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria del Vento', 'Osijek', 35, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Bacio del Mare', 'Slavonski Brod', 5, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Cucina di Pepe', 'Sisak', 26, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino della Taverna', 'Dubrovnik', 48, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Vino di Casa', 'Slavonski Brod', 37, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Locanda dei Sapori', 'Sisak', 6, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Perla del Mare', 'Zagreb', 2, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Cuore del Gusto', 'Vinkovci', 6, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Ristorante da Vinci', 'Dubrovnik', 16, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Finestra del Vino', 'Pula', 32, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Rifugio dei Sapori', 'Dubrovnik', 13, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Corte del Mare', 'Šibenik', 13, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Cucina del Bosco', 'Pula', 12, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria da Leonardo', 'Sisak', 44, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino di Ercole', 'Karlovac', 40, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia Verde', 'Čakovec', 29, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria dei Fiori', 'Pula', 26, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria del Bosco', 'Pula', 48, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Casa di Nonna', 'Slavonski Brod', 20, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto dell''Isola', 'Rijeka', 26, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore del Giardino', 'Slavonski Brod', 7, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Terrazza sul Mare', 'Šibenik', 39, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Ristorante dei Fiori', 'Slavonski Brod', 44, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Dolcezza del Mare', 'Čakovec', 11, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto dei Sogni', 'Rijeka', 47, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Ristorante di Sorrento', 'Osijek', 3, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria del Vecchio Borgo', 'Slavonski Brod', 13, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Taverna del Bosco', 'Slavonski Brod', 33, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore del Vino', 'Varaždin', 25, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia del Gusto', 'Rijeka', 22, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria del Vecchio Castello', 'Varaždin', 32, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto dell''Amore', 'Šibenik', 29, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria della Vigna', 'Dubrovnik', 41, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello del Sole', 'Karlovac', 24, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Taverna di Leonardo', 'Rijeka', 30, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Gusto dell''Oceano', 'Čakovec', 41, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria del Parco', 'Rijeka', 23, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Stanza del Mare', 'Čakovec', 1, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Girasole del Vino', 'Rijeka', 41, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Villa dei Fiori', 'Varaždin', 2, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia d''Oro', 'Čakovec', 16, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello della Luna', 'Vinkovci', 32, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria dei Sogni', 'Slavonski Brod', 50, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino dell''Isola', 'Split', 16, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Tavola del Borgo', 'Vukovar', 20, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Rifugio della Vigna', 'Pula', 16, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria d''Oro', 'Zadar', 38, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore del Sole', 'Šibenik', 35, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Casa del Parco', 'Slavonski Brod', 26, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Torre dei Sapori', 'Šibenik', 41, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria dei Vigneti', 'Šibenik', 30, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello della Tavola', 'Zagreb', 38, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino del Sole', 'Rijeka', 19, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria di Sorrento', 'Osijek', 34, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Castello del Gusto', 'Zadar', 16, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Locanda del Mare', 'Karlovac', 5, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria della Luna', 'Vinkovci', 1, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Giardino dei Sogni', 'Vinkovci', 50, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Baia del Vino', 'Vukovar', 8, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Trattoria del Mare', 'Čakovec', 49, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Casa del Gusto', 'Vukovar', 26, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Sapore della Luna', 'Split', 27, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria dei Mare', 'Karlovac', 19, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Ristorante del Gusto', 'Zadar', 20, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Piazza di Leonardo', 'Rijeka', 11, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Taverna delle Stelle', 'Sisak', 23, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Vino della Trattoria', 'Rijeka', 11, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Bella Trattoria', 'Dubrovnik', 23, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Rifugio del Mare', 'Pula', 15, 'UTO - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Trattoria della Tavola', 'Sisak', 41, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('La Terra del Gusto', 'Zadar', 13, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Il Girasole del Vino', 'Varaždin', 43, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Chevap', 'Zadar', 17, 'PON - NED');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Porcelliono', 'Šibenik', 30, 'PON - SUB');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Podion', 'Dubrovnik', 20, 'PON - PET');
insert into Restaurants (Name, City, Capacity, WorkingTime) values ('Graso', 'Vinkovci', 12, 'PON - SUB');
